// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXVc0MCncL7rM0IOIpkp9vVBQE9k0DS3k',
    appId: '1:460658669000:web:d0b5a0ce6ffc30f60c3cfd',
    messagingSenderId: '460658669000',
    projectId: 'tp-final-dap-gianluca-perrone',
    authDomain: 'tp-final-dap-gianluca-perrone.firebaseapp.com',
    storageBucket: 'tp-final-dap-gianluca-perrone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXVc0MCncL7rM0IOIpkp9vVBQE9k0DS3k',
    appId: '1:460658669000:android:d0b5a0ce6ffc30f60c3cfd',
    messagingSenderId: '460658669000',
    projectId: 'tp-final-dap-gianluca-perrone',
    storageBucket: 'tp-final-dap-gianluca-perrone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXVc0MCncL7rM0IOIpkp9vVBQE9k0DS3k',
    appId: '1:460658669000:ios:d0b5a0ce6ffc30f60c3cfd',
    messagingSenderId: '460658669000',
    projectId: 'tp-final-dap-gianluca-perrone',
    storageBucket: 'tp-final-dap-gianluca-perrone.appspot.com',
    iosBundleId: 'com.example.listas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXVc0MCncL7rM0IOIpkp9vVBQE9k0DS3k',
    appId: '1:460658669000:macos:d0b5a0ce6ffc30f60c3cfd',
    messagingSenderId: '460658669000',
    projectId: 'tp-final-dap-gianluca-perrone',
    storageBucket: 'tp-final-dap-gianluca-perrone.appspot.com',
    iosBundleId: 'com.example.listas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXVc0MCncL7rM0IOIpkp9vVBQE9k0DS3k',
    appId: '1:460658669000:windows:d0b5a0ce6ffc30f60c3cfd',
    messagingSenderId: '460658669000',
    projectId: 'tp-final-dap-gianluca-perrone',
    authDomain: 'tp-final-dap-gianluca-perrone.firebaseapp.com',
    storageBucket: 'tp-final-dap-gianluca-perrone.appspot.com',
  );
}
