// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX5TMFbgR_TfJMYHTe4WuTDMFb59QPxFI',
    appId: '1:1048456945265:web:751434c2d000d241870769',
    messagingSenderId: '1048456945265',
    projectId: 'dap-4tobim',
    authDomain: 'dap-4tobim.firebaseapp.com',
    storageBucket: 'dap-4tobim.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApCVKZv7qh3GryHRkzar8zmFbHaCClrFw',
    appId: '1:1048456945265:android:751434c2d000d241870769',
    messagingSenderId: '1048456945265',
    projectId: 'dap-4tobim',
    storageBucket: 'dap-4tobim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbGmvkeZKLJNo0L6Qat4oAr6tV2nvRGhs',
    appId: '1:1048456945265:ios:751434c2d000d241870769',
    messagingSenderId: '1048456945265',
    projectId: 'dap-4tobim',
    storageBucket: 'dap-4tobim.appspot.com',
    iosBundleId: 'com.example.listas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbGmvkeZKLJNo0L6Qat4oAr6tV2nvRGhs',
    appId: '1:1048456945265:macos:751434c2d000d241870769',
    messagingSenderId: '1048456945265',
    projectId: 'dap-4tobim',
    storageBucket: 'dap-4tobim.appspot.com',
    iosBundleId: 'com.example.listas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX5TMFbgR_TfJMYHTe4WuTDMFb59QPxFI',
    appId: '1:1048456945265:windows:751434c2d000d241870769',
    messagingSenderId: '1048456945265',
    projectId: 'dap-4tobim',
    authDomain: 'dap-4tobim.firebaseapp.com',
    storageBucket: 'dap-4tobim.appspot.com',
  );
}
